dist: bionic
language: generic
git:
  depth: 1

if: (branch = canary-ci OR branch = master) AND (type = push OR type = pull_request)

stages:
  - test
  - name: deploy
    if: type = push

env:
  global:
    - SVC_PREFIX="${AZURE_CONTAINER_REGISTRY}/i40-aas"
  matrix:
    - SERVICE=adapter-registry
    - SERVICE=data-manager
    - SERVICE=endpoint-registry
    - SERVICE=https-endpoint-egress
    - SERVICE=https-endpoint-ingress
    - SERVICE=onboarding-skill
    - SERVICE=storage-adapter-mongodb
    - SERVICE=grpc-endpoint-ingress
    - SERVICE=grpc-endpoint-egress
    - SERVICE=initializer
    - SERVICE=endpoint-resolver

#before_install:
#  - tests here

install:
  - make --version
  - docker --version
  - docker-compose --version

before_script:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
  - if [ $TRAVIS_BRANCH = master ]; then
      SVC_PREFIX="sapi40/i40-aas-";
    else
      openssl aes-256-cbc -K $encrypted_260941c77da3_key -iv $encrypted_260941c77da3_iv -in azure-service-principal.txt.enc -out azure-service-principal.txt -d;
      cat azure-service-principal.txt | docker login $AZURE_CONTAINER_REGISTRY --username $service_principal_id --password-stdin;
    fi

script:
  - make build-single
  - if [ $TRAVIS_EVENT_TYPE = push ]; then
      make push-single;
    fi

jobs:
  include:
    - stage: deploy
      before_deploy:
	- curl -L https://aka.ms/InstallAzureCli | bash
	- curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.10/bin/linux/amd64/kubectl
	- chmod +x ./kubectl
	- sudo mv ./kubectl /usr/local/bin/kubectl
	- (AZ_PASS=$(cat azure-service-principal.txt) && az login --service-principal -u $service_principal_id -p $AZ_PASS --tenant $SAP_TENANT)
	- az aks get-credentials -n i40aas -g i40-aas
#        - kubectl get pods -n aas-${TRAVIS_BRANCH}
	- kubectl config get-contexts
	- curl -LO https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz
	- tar -zxvf helm-v3.1.2-linux-amd64.tar.gz
	- sudo mv linux-amd64/helm /usr/local/bin/helm
	- helm version
#      deploy:
#        - helm update NAME helm/i40-aas/ -f VALUES -n aas-${TRAVIS_BRANCH} && kubectl rollout restart -n aas-${TRAVIS_BRANCH}