version: '3.7'
services:
  ########################################################
  #### i40-aas containers
  ##########################################
  i40-aas-onboarding-skill:
    image: sapi40/i40-aas-onboarding-skill
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## mongodb
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      ## rabbitmq
      - RABBITMQ_AMQP_HOST=${RABBITMQ_AMQP_HOST}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_BROKER_USER=${RABBITMQ_BROKER_USER}
      - RABBITMQ_BROKER_PASSWORD=${RABBITMQ_BROKER_PASSWORD}
      - RABBITMQ_INGRESS_ADMIN_USER=${RABBITMQ_INGRESS_ADMIN_USER}
      - RABBITMQ_INGRESS_ADMIN_PASSWORD=${RABBITMQ_INGRESS_ADMIN_PASSWORD}
      - RABBITMQ_BROKER_EXCHANGE=${RABBITMQ_BROKER_EXCHANGE}
      - RABBITMQ_BROKER_TOPIC_EGRESS=${RABBITMQ_BROKER_TOPIC_EGRESS}
      ## onboarding-skill
      - ONBOARDING_SKILL_REQUEST_APPROVAL=${ONBOARDING_SKILL_REQUEST_APPROVAL}
      - ONBOARDING_SKILL_REQUEST_TYPE=${ONBOARDING_SKILL_REQUEST_TYPE}
      - ONBOARDING_SKILL_STATES_COLLECTION=${ONBOARDING_SKILL_STATES_COLLECTION}
      - ONBOARDING_SKILL_ROOT_TOPIC=${ONBOARDING_SKILL_ROOT_TOPIC}
      - ONBOARDING_SKILL_ROLE=${ONBOARDING_SKILL_ROLE}
      - ONBOARDING_SKILL_URI=${ONBOARDING_SKILL_URI}
      ## data-manager
      - DATA_MANAGER_PROTOCOL=${DATA_MANAGER_PROTOCOL}
      - DATA_MANAGER_HOST=${DATA_MANAGER_HOST}
      - DATA_MANAGER_PORT=${DATA_MANAGER_PORT}
      - DATA_MANAGER_SUBMODELS_ROUTE=${DATA_MANAGER_SUBMODELS_ROUTE}
      - DATA_MANAGER_USER=${DATA_MANAGER_USER}
      - DATA_MANAGER_PASSWORD=${DATA_MANAGER_PASSWORD}
  ##########################################
  i40-aas-https-endpoint-ingress:
    image: sapi40/i40-aas-https-endpoint-ingress
    ports:
      - "2000:2000"
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## rabbitmq
      - RABBITMQ_AMQP_HOST=${RABBITMQ_AMQP_HOST}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_BROKER_USER=${RABBITMQ_BROKER_USER}
      - RABBITMQ_BROKER_PASSWORD=${RABBITMQ_BROKER_PASSWORD}
      - RABBITMQ_INGRESS_ADMIN_USER=${RABBITMQ_INGRESS_ADMIN_USER}
      - RABBITMQ_INGRESS_ADMIN_PASSWORD=${RABBITMQ_INGRESS_ADMIN_PASSWORD}
      - RABBITMQ_BROKER_EXCHANGE=${RABBITMQ_BROKER_EXCHANGE}
      - RABBITMQ_BROKER_TOPIC_EGRESS=${RABBITMQ_BROKER_TOPIC_EGRESS}
      ## https-endpoint-ingress
      - HTTPS_ENDPOINT_INGRESS_PROTOCOL=${HTTPS_ENDPOINT_INGRESS_PROTOCOL}
      - HTTPS_ENDPOINT_INGRESS_HOST=${HTTPS_ENDPOINT_INGRESS_HOST}
      - HTTPS_ENDPOINT_INGRESS_PORT=${HTTPS_ENDPOINT_INGRESS_PORT}
      - HTTPS_ENDPOINT_INGRESS_USER=${HTTPS_ENDPOINT_INGRESS_USER}
      - HTTPS_ENDPOINT_INGRESS_PASSWORD=${HTTPS_ENDPOINT_INGRESS_PASSWORD}
  ##########################################
  i40-aas-https-endpoint-egress:
    image: sapi40/i40-aas-https-endpoint-egress
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## rabbitmq
      - RABBITMQ_AMQP_HOST=${RABBITMQ_AMQP_HOST}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_BROKER_USER=${RABBITMQ_BROKER_USER}
      - RABBITMQ_BROKER_PASSWORD=${RABBITMQ_BROKER_PASSWORD}
      - RABBITMQ_INGRESS_ADMIN_USER=${RABBITMQ_INGRESS_ADMIN_USER}
      - RABBITMQ_INGRESS_ADMIN_PASSWORD=${RABBITMQ_INGRESS_ADMIN_PASSWORD}
      - RABBITMQ_BROKER_EXCHANGE=${RABBITMQ_BROKER_EXCHANGE}
      - RABBITMQ_BROKER_TOPIC_EGRESS=${RABBITMQ_BROKER_TOPIC_EGRESS}
      ## endpoint-registry
      - ENDPOINT_REGISTRY_PROTOCOL=${ENDPOINT_REGISTRY_PROTOCOL}
      - ENDPOINT_REGISTRY_HOST=${ENDPOINT_REGISTRY_HOST}
      - ENDPOINT_REGISTRY_PORT=${ENDPOINT_REGISTRY_PORT}
      - ENDPOINT_REGISTRY_URL_SUFFIX=${ENDPOINT_REGISTRY_URL_SUFFIX}
      - ENDPOINT_REGISTRY_ADMIN_USER=${ENDPOINT_REGISTRY_ADMIN_USER}
      - ENDPOINT_REGISTRY_ADMIN_PASSWORD=${ENDPOINT_REGISTRY_ADMIN_PASSWORD}
  ##########################################
  i40-aas-grpc-endpoint-ingress:
    image: sapi40/i40-aas-grpc-endpoint-ingress
    ports:
      - "8384:8384"
    volumes:
      - .compose/volumes/grpc-endpoint-ingress:/grpc-endpoint-ingress
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## rabbitmq
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_INGRESS_USER=${RABBITMQ_INGRESS_USER}
      - RABBITMQ_INGRESS_PASSWORD=${RABBITMQ_INGRESS_PASSWORD}
      - RABBITMQ_INGRESS_EXCHANGE=${RABBITMQ_INGRESS_EXCHANGE}
      ## grpc-endpoint-ingress
      - GRPC_ENDPOINT_INGRESS_PORT=${GRPC_ENDPOINT_INGRESS_PORT}
  # ##########################################
  i40-aas-grpc-endpoint-egress:
    image: sapi40/i40-aas-grpc-endpoint-egress
    volumes:
      - .compose/volumes/grpc-endpoint-egress:/grpc-endpoint-egress
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## rabbitmq
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_EGRESS_USER=${RABBITMQ_EGRESS_USER}
      - RABBITMQ_EGRESS_PASSWORD=${RABBITMQ_EGRESS_PASSWORD}
      - RABBITMQ_EGRESS_EXCHANGE=${RABBITMQ_EGRESS_EXCHANGE}
      ## grpc-endpoint-egress
      - GRPC_ENDPOINT_EGRESS_AMQP_QUEUE=${GRPC_ENDPOINT_EGRESS_AMQP_QUEUE}
      - GRPC_ENDPOINT_EGRESS_AMQP_CTAG=${GRPC_ENDPOINT_EGRESS_AMQP_CTAG}
  # ##########################################
  i40-aas-endpoint-resolver:
    image: sapi40/i40-aas-endpoint-resolver
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## rabbitmq
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_EGRESS_USER=${RABBITMQ_EGRESS_USER}
      - RABBITMQ_EGRESS_PASSWORD=${RABBITMQ_EGRESS_PASSWORD}
      - RABBITMQ_EGRESS_EXCHANGE=${RABBITMQ_EGRESS_EXCHANGE}
      ## endpoint-resolver
      - ENDPOINT_RESOLVER_AMQP_QUEUE=${ENDPOINT_RESOLVER_AMQP_QUEUE}
      ## endpoint-registry
      - ENDPOINT_REGISTRY_PROTOCOL=${ENDPOINT_REGISTRY_PROTOCOL}
      - ENDPOINT_REGISTRY_HOST=${ENDPOINT_REGISTRY_HOST}
      - ENDPOINT_REGISTRY_PORT=${ENDPOINT_REGISTRY_PORT}
      - ENDPOINT_REGISTRY_URL_SUFFIX=${ENDPOINT_REGISTRY_URL_SUFFIX}
      - ENDPOINT_REGISTRY_ADMIN_USER=${ENDPOINT_REGISTRY_ADMIN_USER}
      - ENDPOINT_REGISTRY_ADMIN_PASSWORD=${ENDPOINT_REGISTRY_ADMIN_PASSWORD}
  ##########################################
  i40-aas-data-manager:
    image: sapi40/i40-aas-data-manager
    ports:
      - "4000:4000"
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## adapter-registry
      - ADAPTER_REGISTRY_PROTOCOL=${ADAPTER_REGISTRY_PROTOCOL}
      - ADAPTER_REGISTRY_HOST=${ADAPTER_REGISTRY_HOST}
      - ADAPTER_REGISTRY_PORT=${ADAPTER_REGISTRY_PORT}
      - ADAPTER_REGISTRY_URL_SUFFIX=${ADAPTER_REGISTRY_URL_SUFFIX}
      - ADAPTER_REGISTRY_ADMIN_USER=${ADAPTER_REGISTRY_ADMIN_USER}
      - ADAPTER_REGISTRY_ADMIN_PASSWORD=${ADAPTER_REGISTRY_ADMIN_PASSWORD}
      ## data-manager
      - DATA_MANAGER_PROTOCOL=${DATA_MANAGER_PROTOCOL}
      - DATA_MANAGER_HOST=${DATA_MANAGER_HOST}
      - DATA_MANAGER_PORT=${DATA_MANAGER_PORT}
      - DATA_MANAGER_SUBMODELS_ROUTE=${DATA_MANAGER_SUBMODELS_ROUTE}
      - DATA_MANAGER_USER=${DATA_MANAGER_USER}
      - DATA_MANAGER_PASSWORD=${DATA_MANAGER_PASSWORD}
  ##########################################
  i40-aas-endpoint-registry:
    image: sapi40/i40-aas-endpoint-registry
    ports:
      - "4400:4400"
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## postgres
      - ENDPOINT_REGISTRY_POSTGRES_HOST=${ENDPOINT_REGISTRY_POSTGRES_HOST}
      - ENDPOINT_REGISTRY_POSTGRES_PORT=${ENDPOINT_REGISTRY_POSTGRES_PORT}
      - ENDPOINT_REGISTRY_POSTGRES_USER=${ENDPOINT_REGISTRY_POSTGRES_USER}
      - ENDPOINT_REGISTRY_POSTGRES_PASSWORD=${ENDPOINT_REGISTRY_POSTGRES_PASSWORD}
      - ENDPOINT_REGISTRY_POSTGRES_DB=${ENDPOINT_REGISTRY_POSTGRES_DB}
      ## endpoint-registry
      - ENDPOINT_REGISTRY_PROTOCOL=${ENDPOINT_REGISTRY_PROTOCOL}
      - ENDPOINT_REGISTRY_HOST=${ENDPOINT_REGISTRY_HOST}
      - ENDPOINT_REGISTRY_PORT=${ENDPOINT_REGISTRY_PORT}
      - ENDPOINT_REGISTRY_URL_SUFFIX=${ENDPOINT_REGISTRY_URL_SUFFIX}
      - ENDPOINT_REGISTRY_ADMIN_USER=${ENDPOINT_REGISTRY_ADMIN_USER}
      - ENDPOINT_REGISTRY_ADMIN_PASSWORD=${ENDPOINT_REGISTRY_ADMIN_PASSWORD}
  ##########################################
  i40-aas-adapter-registry:
    image: sapi40/i40-aas-adapter-registry
    ports:
      - "4500:4500"
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## adapter-registry
      - ADAPTER_REGISTRY_PROTOCOL=${ADAPTER_REGISTRY_PROTOCOL}
      - ADAPTER_REGISTRY_HOST=${ADAPTER_REGISTRY_HOST}
      - ADAPTER_REGISTRY_PORT=${ADAPTER_REGISTRY_PORT}
      - ADAPTER_REGISTRY_URL_SUFFIX=${ADAPTER_REGISTRY_URL_SUFFIX}
      - ADAPTER_REGISTRY_ADMIN_USER=${ADAPTER_REGISTRY_ADMIN_USER}
      - ADAPTER_REGISTRY_ADMIN_PASSWORD=${ADAPTER_REGISTRY_ADMIN_PASSWORD}
  ##########################################
  i40-aas-storage-adapter-mongodb:
    image: sapi40/i40-aas-storage-adapter-mongodb
    ports:
      - "3100:3100"
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## mongodb
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      ## storage-adapter-mongodb
      - STORAGE_ADAPTER_MONGODB_PORT=${STORAGE_ADAPTER_MONGODB_PORT}
      - STORAGE_ADAPTER_MONGODB_SUBOMODELS_COLLECTION=${STORAGE_ADAPTER_MONGODB_SUBOMODELS_COLLECTION}
  ##########################################
  i40-aas-initializer:
    image: sapi40/i40-aas-initializer
    volumes:
      - .compose/volumes/initializer/:/initializer
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## postgres
      - ENDPOINT_REGISTRY_POSTGRES_HOST=${ENDPOINT_REGISTRY_POSTGRES_HOST}
      - ENDPOINT_REGISTRY_POSTGRES_PORT=${ENDPOINT_REGISTRY_POSTGRES_PORT}
      ## rabbitmq
      - RABBITMQ_AMQP_HOST=${RABBITMQ_AMQP_HOST}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_AMQP_PORT}
      ## mongodb
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      ## data-manager
      - DATA_MANAGER_HOST=${DATA_MANAGER_HOST}
      - DATA_MANAGER_PORT=${DATA_MANAGER_PORT}
      ## adapter-registry
      - ADAPTER_REGISTRY_HOST=${ADAPTER_REGISTRY_HOST}
      - ADAPTER_REGISTRY_PORT=${ADAPTER_REGISTRY_PORT}
      ## endpoint-registry
      - ENDPOINT_REGISTRY_HOST=${ENDPOINT_REGISTRY_HOST}
      - ENDPOINT_REGISTRY_PORT=${ENDPOINT_REGISTRY_PORT}
      ## endpoint-resolver
      # - =${}
      ## https-endpoint-ingress
      - HTTPS_ENDPOINT_INGRESS_HOST=${HTTPS_ENDPOINT_INGRESS_HOST}
      - HTTPS_ENDPOINT_INGRESS_PORT=${HTTPS_ENDPOINT_INGRESS_PORT}
      ## grpc-endpoint-ingress
      - GRPC_ENDPOINT_INGRESS_HOST=${GRPC_ENDPOINT_INGRESS_HOST}
      - GRPC_ENDPOINT_INGRESS_PORT=${GRPC_ENDPOINT_INGRESS_PORT}
      ## grpc-endpoint-egress
      # - =${}

  ########################################################
  #### third party services
  ##########################################
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      ## mongodb
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
  ##########################################
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      ## postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  ##########################################
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
    volumes:
      - .compose/volumes/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
