version: '3.7'
services:
  ########################################################
  #### i40-aas containers
  ##########################################
  i40-aas-onboarding-skill:
    image: sapi40/i40-aas-onboarding-skill
    environment:
      ## logging
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      ## mongodb
      - SKILLS_ONBOARDING_DATABASE_HOST=mongodb
      - SKILLS_ONBOARDING_DATABASE_PORT=${SKILLS_ONBOARDING_DATABASE_PORT}
      - SKILLS_ONBOARDING_DATABASE_USER=${SKILLS_ONBOARDING_DATABASE_USER}
      - SKILLS_ONBOARDING_DATABASE_PASSWORD=${SKILLS_ONBOARDING_DATABASE_PASSWORD}
      - SKILLS_ONBOARDING_DATABASE_NAME=${SKILLS_ONBOARDING_DATABASE_NAME}
      ## rabbitmq
      - CORE_BROKER_HOST=rabbitmq
      - CORE_EGRESS_USER=${CORE_EGRESS_USER}
      - CORE_EGRESS_PASSWORD=${CORE_EGRESS_PASSWORD}
      - CORE_EGRESS_EXCHANGE=${CORE_EGRESS_EXCHANGE}
      - CORE_INGRESS_EXCHANGE=${CORE_INGRESS_EXCHANGE}
      - CORE_INGRESS_USER=${CORE_INGRESS_USER}
      - CORE_INGRESS_PASSWORD=${CORE_INGRESS_PASSWORD}
      - CORE_ENDPOINT_RESOLVER_QUEUE=egress.generic
      ## onboarding-skill
      - SKILLS_ONBOARDING_APPROVAL_ENABLED=${SKILLS_ONBOARDING_APPROVAL_ENABLED}
      - SKILLS_ONBOARDING_APPROVAL_TYPE=${SKILLS_ONBOARDING_APPROVAL_TYPE}
      - SKILLS_ONBOARDING_APPROVAL_STATES_COLLECTION=${SKILLS_ONBOARDING_APPROVAL_STATES_COLLECTION}
      - SKILLS_ONBOARDING_APPROVAL_ROOT_TOPIC=${SKILLS_ONBOARDING_APPROVAL_ROOT_TOPIC}
      - SKILLS_ONBOARDING_APPROVAL_ROLE=${SKILLS_ONBOARDING_APPROVAL_ROLE}
      - SKILLS_ONBOARDING_APPROVAL_URI=${SKILLS_ONBOARDING_APPROVAL_URI}
      ## data-manager
      - CORE_DATA_MANAGER_PROTOCOL=http
      - CORE_DATA_MANAGER_HOST=i40-aas-data-manager
      - CORE_DATA_MANAGER_PORT=${CORE_DATA_MANAGER_PORT}
      - CORE_DATA_MANAGER_SUBMODELS_ROUTE=${CORE_DATA_MANAGER_SUBMODELS_ROUTE}
      - CORE_DATA_MANAGER_USER=${CORE_DATA_MANAGER_USER}
      - CORE_DATA_MANAGER_PASSWORD=${CORE_DATA_MANAGER_PASSWORD}
  ##########################################
  i40-aas-https-endpoint-ingress:
    image: sapi40/i40-aas-https-endpoint-ingress
    ports:
      - "${CORE_INGRESS_HTTP_PORT}:${CORE_INGRESS_HTTP_PORT}"
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## rabbitmq
      - RABBITMQ_AMQP_HOST=${RABBITMQ_AMQP_HOST}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_BROKER_USER=${RABBITMQ_BROKER_USER}
      - RABBITMQ_BROKER_PASSWORD=${RABBITMQ_BROKER_PASSWORD}
      - RABBITMQ_INGRESS_ADMIN_USER=${RABBITMQ_INGRESS_ADMIN_USER}
      - RABBITMQ_INGRESS_ADMIN_PASSWORD=${RABBITMQ_INGRESS_ADMIN_PASSWORD}
      - RABBITMQ_BROKER_EXCHANGE=${RABBITMQ_BROKER_EXCHANGE}
      - RABBITMQ_BROKER_TOPIC_EGRESS=${RABBITMQ_BROKER_TOPIC_EGRESS}
      ## https-endpoint-ingress
      - HTTPS_ENDPOINT_INGRESS_PROTOCOL=${HTTPS_ENDPOINT_INGRESS_PROTOCOL}
      - HTTPS_ENDPOINT_INGRESS_HOST=${HTTPS_ENDPOINT_INGRESS_HOST}
      - HTTPS_ENDPOINT_INGRESS_PORT=${HTTPS_ENDPOINT_INGRESS_PORT}
      - HTTPS_ENDPOINT_INGRESS_USER=${HTTPS_ENDPOINT_INGRESS_USER}
      - HTTPS_ENDPOINT_INGRESS_PASSWORD=${HTTPS_ENDPOINT_INGRESS_PASSWORD}
  ##########################################
  i40-aas-https-endpoint-egress:
    image: sapi40/i40-aas-https-endpoint-egress
    environment:
      ## logging
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT=${LOG_OUTPUT}
      ## rabbitmq
      - RABBITMQ_AMQP_HOST=${RABBITMQ_HOST}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_PORT}
      - RABBITMQ_BROKER_USER=${RABBITMQ_EGRESS_USER}
      - RABBITMQ_BROKER_PASSWORD=${RABBITMQ_EGRESS_PASSWORD}
      - RABBITMQ_BROKER_EXCHANGE=${RABBITMQ_EGRESS_EXCHANGE}
      - RABBITMQ_BROKER_TOPIC_EGRESS=${HTTPS_ENDPOINT_EGRESS_AMQP_QUEUE}
      ## endpoint-registry
      - ENDPOINT_REGISTRY_PROTOCOL=${ENDPOINT_REGISTRY_PROTOCOL}
      - ENDPOINT_REGISTRY_HOST=${ENDPOINT_REGISTRY_HOST}
      - ENDPOINT_REGISTRY_PORT=${ENDPOINT_REGISTRY_PORT}
      - ENDPOINT_REGISTRY_URL_SUFFIX=${ENDPOINT_REGISTRY_URL_SUFFIX}
      - ENDPOINT_REGISTRY_ADMIN_USER=${ENDPOINT_REGISTRY_ADMIN_USER}
      - ENDPOINT_REGISTRY_ADMIN_PASSWORD=${ENDPOINT_REGISTRY_ADMIN_PASSWORD}
  ##########################################
  i40-aas-grpc-endpoint-ingress:
    image: sapi40/i40-aas-grpc-endpoint-ingress
    ports:
      - "${CORE_INGRESS_GRPC_PORT}:${CORE_INGRESS_GRPC_PORT}"
    environment:
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      - CORE_BROKER_HOST=rabbitmq
      - CORE_BROKER_PORT=${CORE_BROKER_PORT}
      - CORE_INGRESS_USER=${CORE_INGRESS_USER}
      - CORE_INGRESS_PASSWORD=${CORE_INGRESS_PASSWORD}
      - CORE_INGRESS_EXCHANGE=${CORE_INGRESS_EXCHANGE}
      - CORE_INGRESS_GRPC_PORT=${CORE_INGRESS_GRPC_PORT}
  ##########################################
  i40-aas-grpc-endpoint-egress:
    image: sapi40/i40-aas-grpc-endpoint-egress
    environment:
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      - CORE_BROKER_HOST=rabbitmq
      - CORE_BROKER_PORT=${CORE_BROKER_PORT}
      - CORE_EGRESS_USER=${CORE_EGRESS_USER}
      - CORE_EGRESS_PASSWORD=${CORE_EGRESS_PASSWORD}
      - CORE_EGRESS_EXCHANGE=${CORE_EGRESS_EXCHANGE}
      - CORE_EGRESS_GRPC_QUEUE=${CORE_EGRESS_GRPC_QUEUE}
      - CORE_EGRESS_GRPC_CTAG=${CORE_EGRESS_GRPC_CTAG}
  ##########################################
  i40-aas-endpoint-resolver:
    image: sapi40/i40-aas-endpoint-resolver
    environment:
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      - CORE_BROKER_HOST=rabbitmq
      - CORE_BROKER_PORT=${CORE_BROKER_PORT}
      - CORE_EGRESS_USER=${CORE_EGRESS_USER}
      - CORE_EGRESS_PASSWORD=${CORE_EGRESS_PASSWORD}
      - CORE_EGRESS_EXCHANGE=${CORE_EGRESS_EXCHANGE}
      - CORE_ENDPOINT_RESOLVER_CTAG=${CORE_ENDPOINT_RESOLVER_CTAG}
      - CORE_ENDPOINT_RESOLVER_QUEUE=${CORE_ENDPOINT_RESOLVER_QUEUE}
      - CORE_REGISTRIES_ENDPOINTS_HOST=i40-aas-endpoint-registry
      - CORE_REGISTRIES_ENDPOINTS_PORT=${CORE_REGISTRIES_ENDPOINTS_PORT}
      - CORE_REGISTRIES_ENDPOINTS_URL_SUFFIX=${CORE_REGISTRIES_ENDPOINTS_URL_SUFFIX}
      - CORE_REGISTRIES_ENDPOINTS_USER=${CORE_REGISTRIES_ENDPOINTS_USER}
      - CORE_REGISTRIES_ENDPOINTS_PASSWORD=${CORE_REGISTRIES_ENDPOINTS_PASSWORD}
  ##########################################
  i40-aas-data-manager:
    image: sapi40/i40-aas-data-manager
    ports:
      - "${CORE_DATA_MANAGER_PORT}:${CORE_DATA_MANAGER_PORT}"
    environment:
      ## logging
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      ## adapter-registry
      - CORE_REGISTRIES_ADAPTERS_PROTOCOL=http
      - CORE_REGISTRIES_ADAPTERS_HOST=i40-aas-adapter-registry
      - CORE_REGISTRIES_ADAPTERS_PORT=${CORE_REGISTRIES_ADAPTERS_PORT}
      - CORE_REGISTRIES_ADAPTERS_URL_SUFFIX=${CORE_REGISTRIES_ADAPTERS_URL_SUFFIX}
      - CORE_REGISTRIES_ADAPTERS_USER=${CORE_REGISTRIES_ADAPTERS_USER}
      - CORE_REGISTRIES_ADAPTERS_PASSWORD=${CORE_REGISTRIES_ADAPTERS_PASSWORD}
      ## data-manager
      - CORE_DATA_MANAGER_USER=${CORE_DATA_MANAGER_USER}
      - CORE_DATA_MANAGER_PASSWORD=${CORE_DATA_MANAGER_PASSWORD}
  ##########################################
  i40-aas-endpoint-registry:
    image: sapi40/i40-aas-endpoint-registry
    ports:
      - "${CORE_REGISTRIES_ENDPOINTS_PORT}:${CORE_REGISTRIES_ENDPOINTS_PORT}"
    environment:
      ## logging
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      ## postgres
      - CORE_REGISTRIES_ENDPOINTS_DATABASE_HOST=endpoint-registry-postgres
      - CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT=${CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT}
      - CORE_REGISTRIES_ENDPOINTS_DATABASE_USER=${CORE_REGISTRIES_ENDPOINTS_DATABASE_USER}
      - CORE_REGISTRIES_ENDPOINTS_DATABASE_PASSWORD=${CORE_REGISTRIES_ENDPOINTS_DATABASE_PASSWORD}
      - CORE_REGISTRIES_ENDPOINTS_DATABASE_NAME=${CORE_REGISTRIES_ENDPOINTS_DATABASE_NAME}
      ## endpoint-registry
      - CORE_REGISTRIES_ENDPOINTS_USER=${CORE_REGISTRIES_ENDPOINTS_USER}
      - CORE_REGISTRIES_ENDPOINTS_PASSWORD=${CORE_REGISTRIES_ENDPOINTS_PASSWORD}
  ##########################################
  i40-aas-adapter-registry:
    image: sapi40/i40-aas-adapter-registry
    ports:
      - "${CORE_REGISTRIES_ADAPTERS_PORT}:${CORE_REGISTRIES_ADAPTERS_PORT}"
    environment:
      ## logging
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      ## adapter-registry
      - CORE_REGISTRIES_ADAPTERS_USER=${CORE_REGISTRIES_ADAPTERS_USER}
      - CORE_REGISTRIES_ADAPTERS_PASSWORD=${CORE_REGISTRIES_ADAPTERS_PASSWORD}
  ##########################################
  i40-aas-storage-adapter-mongodb:
    image: sapi40/i40-aas-storage-adapter-mongodb
    ports:
      - "${APPLICATION_ADAPTERS_MONGODB_PORT}:${APPLICATION_ADAPTERS_MONGODB_PORT}"
    environment:
      ## logging
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      ## mongodb
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=${SKILLS_ONBOARDING_DATABASE_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${SKILLS_ONBOARDING_DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${SKILLS_ONBOARDING_DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${SKILLS_ONBOARDING_DATABASE_NAME}
      ## storage-adapter-mongodb
      - APPLICATION_ADAPTERS_MONGODB_SUBMODELS_COLLECTION=${APPLICATION_ADAPTERS_MONGODB_SUBMODELS_COLLECTION}
  ##########################################
  i40-aas-initializer:
    image: sapi40/i40-aas-initializer
    volumes:
      - .compose/volumes/initializer/:/initializer
    environment:
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      - CORE_BROKER_HOST=rabbitmq
      - CORE_BROKER_PORT=${CORE_BROKER_PORT}
      - CORE_REGISTRIES_ENDPOINTS_DATABASE_HOST=endpoint-registry-postgres
      - CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT=${CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT}
      - CORE_REGISTRIES_ENDPOINTS_HOST=i40-aas-endpoint-registry
      - CORE_REGISTRIES_ENDPOINTS_PORT=${CORE_REGISTRIES_ENDPOINTS_PORT}
      - CORE_DATA_MANAGER_HOST=i40-aas-data-manager
      - CORE_DATA_MANAGER_PORT=${CORE_DATA_MANAGER_PORT}
      - APPLICATION_ADAPTERS_MONGODB_HOST=mongodb
      - APPLICATION_ADAPTERS_MONGODB_PORT=${APPLICATION_ADAPTERS_MONGODB_PORT}
      - CORE_REGISTRIES_ADAPTERS_HOST=i40-aas-adapter-registry
      - CORE_REGISTRIES_ADAPTERS_PORT=${CORE_REGISTRIES_ADAPTERS_PORT}
      - CORE_INGRESS_HTTP_HOST=i40-aas-https-endpoint-ingress
      - CORE_INGRESS_HTTP_PORT=${CORE_INGRESS_HTTP_PORT}
      - CORE_INGRESS_GRPC_HOST=i40-aas-grpc-endpoint-ingress
      - CORE_INGRESS_GRPC_PORT=${CORE_INGRESS_GRPC_PORT}
      ## TODO: add endpoint-resolver, http-endpoint-egress and grpc-endpoint-egress
      ## once healthchecks are added
      # - =${}



  ########################################################
  #### third party containers
  ##########################################
  mongodb:
    image: mongo
    ports:
      - "${SKILLS_ONBOARDING_DATABASE_PORT}:${SKILLS_ONBOARDING_DATABASE_PORT}"
    environment:
      ## mongodb
      - MONGO_INITDB_ROOT_USERNAME=${SKILLS_ONBOARDING_DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${SKILLS_ONBOARDING_DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${SKILLS_ONBOARDING_DATABASE_NAME}
  ##########################################
  endpoint-registry-postgres:
    image: postgres:alpine
    ports:
      - "${CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT}:${CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${CORE_REGISTRIES_ENDPOINTS_DATABASE_SUPER_USER}
      - POSTGRES_PASSWORD=${CORE_REGISTRIES_ENDPOINTS_DATABASE_SUPER_PASSWORD}
  ##########################################
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${CORE_BROKER_PORT}:${CORE_BROKER_PORT}"
      - "${CORE_BROKER_PORT_UI}:${CORE_BROKER_PORT_UI}"
      - "${CORE_BROKER_PORT_MQTT}:${CORE_BROKER_PORT_MQTT}"
    volumes:
      - .compose/volumes/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
